version: '3'

services:

  db:
    build: docker-context/scoreboard-db/
    environment:
      POSTGRES_DB: scoreboard
      POSTGRES_PASSWORD: test
      POSTGRES_USER: scoreboard
    ports:
      - 5433:5432

  osmesa:
    build: docker-context/osmesa-mock/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5434:5432

  wait-for-db-ready:
    image: dadarek/wait-for-dependencies
    environment:
      SLEEP_LENGTH: 10
      TIMEOUT_LENGTH: 600
    depends_on:
      - osmesa
      - db
    command: osmesa:5432 db:5432
