version: '2'

services:
  db:
    image: mdillon/postgis:9.6-alpine
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: scoreboard
      POSTGRES_DB: scoreboard
    ports:
      - 5433:5432 
    volumes:
      - './.tmp/pg:/var/lib/postgresql/data'
