version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout

      - restore_cache:
          keys:
            - scoreboard-{{ checksum "package.json" }}-{{ checksum "api/package.json" }}-{{ checksum "frontend/package.json" }}

      - run:
          name: Install
          command: yarn 
      - run:
          name: Bootstrap
          command: yarn bootstrap
      - run:
          name: Lint
          command: yarn eslint

      - save_cache:
          key: scoreboard-{{ checksum "package.json" }}-{{ checksum "api/package.json" }}-{{ checksum "frontend/package.json" }}
          paths:
            - ~/node_modules
            - ~/api/node_modules
            - ~/frontend/node_modules