version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run:
          name: Install
          command: yarn 
      - run:
          name: Bootstrap
          command: yarn bootstrap
      - run:
          name: Lint
          command: yarn eslint